//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereHouse.WarehouseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WarehouseServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name productName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        WereHouse.WarehouseServiceReference.AddProductResponse AddProduct(WereHouse.WarehouseServiceReference.AddProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.AddProductResponse> AddProductAsync(WereHouse.WarehouseServiceReference.AddProductRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteProductResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        WereHouse.WarehouseServiceReference.DeleteProductResponse DeleteProduct(WereHouse.WarehouseServiceReference.DeleteProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.DeleteProductResponse> DeleteProductAsync(WereHouse.WarehouseServiceReference.DeleteProductRequest request);
        
        // CODEGEN: Generating message contract since element name productName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        WereHouse.WarehouseServiceReference.UpdateProductResponse UpdateProduct(WereHouse.WarehouseServiceReference.UpdateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.UpdateProductResponse> UpdateProductAsync(WereHouse.WarehouseServiceReference.UpdateProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProduct", Namespace="http://tempuri.org/", Order=0)]
        public WereHouse.WarehouseServiceReference.AddProductRequestBody Body;
        
        public AddProductRequest() {
        }
        
        public AddProductRequest(WereHouse.WarehouseServiceReference.AddProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal price;
        
        public AddProductRequestBody() {
        }
        
        public AddProductRequestBody(string productName, string description, int quantity, decimal price) {
            this.productName = productName;
            this.description = description;
            this.quantity = quantity;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public WereHouse.WarehouseServiceReference.AddProductResponseBody Body;
        
        public AddProductResponse() {
        }
        
        public AddProductResponse(WereHouse.WarehouseServiceReference.AddProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddProductResult;
        
        public AddProductResponseBody() {
        }
        
        public AddProductResponseBody(string AddProductResult) {
            this.AddProductResult = AddProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProduct", Namespace="http://tempuri.org/", Order=0)]
        public WereHouse.WarehouseServiceReference.DeleteProductRequestBody Body;
        
        public DeleteProductRequest() {
        }
        
        public DeleteProductRequest(WereHouse.WarehouseServiceReference.DeleteProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        public DeleteProductRequestBody() {
        }
        
        public DeleteProductRequestBody(int productId) {
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public WereHouse.WarehouseServiceReference.DeleteProductResponseBody Body;
        
        public DeleteProductResponse() {
        }
        
        public DeleteProductResponse(WereHouse.WarehouseServiceReference.DeleteProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteProductResult;
        
        public DeleteProductResponseBody() {
        }
        
        public DeleteProductResponseBody(string DeleteProductResult) {
            this.DeleteProductResult = DeleteProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProduct", Namespace="http://tempuri.org/", Order=0)]
        public WereHouse.WarehouseServiceReference.UpdateProductRequestBody Body;
        
        public UpdateProductRequest() {
        }
        
        public UpdateProductRequest(WereHouse.WarehouseServiceReference.UpdateProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal price;
        
        public UpdateProductRequestBody() {
        }
        
        public UpdateProductRequestBody(int productId, string productName, string description, int quantity, decimal price) {
            this.productId = productId;
            this.productName = productName;
            this.description = description;
            this.quantity = quantity;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public WereHouse.WarehouseServiceReference.UpdateProductResponseBody Body;
        
        public UpdateProductResponse() {
        }
        
        public UpdateProductResponse(WereHouse.WarehouseServiceReference.UpdateProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateProductResult;
        
        public UpdateProductResponseBody() {
        }
        
        public UpdateProductResponseBody(string UpdateProductResult) {
            this.UpdateProductResult = UpdateProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WereHouse.WarehouseServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WereHouse.WarehouseServiceReference.WebService1Soap>, WereHouse.WarehouseServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WereHouse.WarehouseServiceReference.AddProductResponse WereHouse.WarehouseServiceReference.WebService1Soap.AddProduct(WereHouse.WarehouseServiceReference.AddProductRequest request) {
            return base.Channel.AddProduct(request);
        }
        
        public string AddProduct(string productName, string description, int quantity, decimal price) {
            WereHouse.WarehouseServiceReference.AddProductRequest inValue = new WereHouse.WarehouseServiceReference.AddProductRequest();
            inValue.Body = new WereHouse.WarehouseServiceReference.AddProductRequestBody();
            inValue.Body.productName = productName;
            inValue.Body.description = description;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            WereHouse.WarehouseServiceReference.AddProductResponse retVal = ((WereHouse.WarehouseServiceReference.WebService1Soap)(this)).AddProduct(inValue);
            return retVal.Body.AddProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.AddProductResponse> WereHouse.WarehouseServiceReference.WebService1Soap.AddProductAsync(WereHouse.WarehouseServiceReference.AddProductRequest request) {
            return base.Channel.AddProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.AddProductResponse> AddProductAsync(string productName, string description, int quantity, decimal price) {
            WereHouse.WarehouseServiceReference.AddProductRequest inValue = new WereHouse.WarehouseServiceReference.AddProductRequest();
            inValue.Body = new WereHouse.WarehouseServiceReference.AddProductRequestBody();
            inValue.Body.productName = productName;
            inValue.Body.description = description;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            return ((WereHouse.WarehouseServiceReference.WebService1Soap)(this)).AddProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WereHouse.WarehouseServiceReference.DeleteProductResponse WereHouse.WarehouseServiceReference.WebService1Soap.DeleteProduct(WereHouse.WarehouseServiceReference.DeleteProductRequest request) {
            return base.Channel.DeleteProduct(request);
        }
        
        public string DeleteProduct(int productId) {
            WereHouse.WarehouseServiceReference.DeleteProductRequest inValue = new WereHouse.WarehouseServiceReference.DeleteProductRequest();
            inValue.Body = new WereHouse.WarehouseServiceReference.DeleteProductRequestBody();
            inValue.Body.productId = productId;
            WereHouse.WarehouseServiceReference.DeleteProductResponse retVal = ((WereHouse.WarehouseServiceReference.WebService1Soap)(this)).DeleteProduct(inValue);
            return retVal.Body.DeleteProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.DeleteProductResponse> WereHouse.WarehouseServiceReference.WebService1Soap.DeleteProductAsync(WereHouse.WarehouseServiceReference.DeleteProductRequest request) {
            return base.Channel.DeleteProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.DeleteProductResponse> DeleteProductAsync(int productId) {
            WereHouse.WarehouseServiceReference.DeleteProductRequest inValue = new WereHouse.WarehouseServiceReference.DeleteProductRequest();
            inValue.Body = new WereHouse.WarehouseServiceReference.DeleteProductRequestBody();
            inValue.Body.productId = productId;
            return ((WereHouse.WarehouseServiceReference.WebService1Soap)(this)).DeleteProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WereHouse.WarehouseServiceReference.UpdateProductResponse WereHouse.WarehouseServiceReference.WebService1Soap.UpdateProduct(WereHouse.WarehouseServiceReference.UpdateProductRequest request) {
            return base.Channel.UpdateProduct(request);
        }
        
        public string UpdateProduct(int productId, string productName, string description, int quantity, decimal price) {
            WereHouse.WarehouseServiceReference.UpdateProductRequest inValue = new WereHouse.WarehouseServiceReference.UpdateProductRequest();
            inValue.Body = new WereHouse.WarehouseServiceReference.UpdateProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.productName = productName;
            inValue.Body.description = description;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            WereHouse.WarehouseServiceReference.UpdateProductResponse retVal = ((WereHouse.WarehouseServiceReference.WebService1Soap)(this)).UpdateProduct(inValue);
            return retVal.Body.UpdateProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.UpdateProductResponse> WereHouse.WarehouseServiceReference.WebService1Soap.UpdateProductAsync(WereHouse.WarehouseServiceReference.UpdateProductRequest request) {
            return base.Channel.UpdateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<WereHouse.WarehouseServiceReference.UpdateProductResponse> UpdateProductAsync(int productId, string productName, string description, int quantity, decimal price) {
            WereHouse.WarehouseServiceReference.UpdateProductRequest inValue = new WereHouse.WarehouseServiceReference.UpdateProductRequest();
            inValue.Body = new WereHouse.WarehouseServiceReference.UpdateProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.productName = productName;
            inValue.Body.description = description;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            return ((WereHouse.WarehouseServiceReference.WebService1Soap)(this)).UpdateProductAsync(inValue);
        }
    }
}
